-- Shared exercise catalog. Ids are derived from the name so they are stable
-- across environments and re-seeding.

INSERT INTO exercises (id, owner_id, name, tracking, primary_muscle, secondary_muscles, equipment, difficulty)
SELECT md5('fittune:exercise:' || lower(name))::uuid, NULL, name, tracking, primary_muscle, secondary_muscles, equipment, difficulty
FROM (VALUES
    ('Barbell Bench Press',            'weight_reps',       'chest',       ARRAY['triceps', 'shoulders'],                 'barbell',    'intermediate'),
    ('Incline Dumbbell Press',         'weight_reps',       'chest',       ARRAY['shoulders', 'triceps'],                 'dumbbell',   'beginner'),
    ('Dumbbell Fly',                   'weight_reps',       'chest',       ARRAY['shoulders'],                            'dumbbell',   'beginner'),
    ('Cable Crossover',                'weight_reps',       'chest',       ARRAY['shoulders'],                            'cable',      'beginner'),
    ('Push-Up',                        'reps',              'chest',       ARRAY['triceps', 'shoulders', 'abs'],          'none',       'beginner'),
    ('Chest Dip',                      'reps',              'chest',       ARRAY['triceps', 'shoulders'],                 'none',       'intermediate'),
    ('Barbell Back Squat',             'weight_reps',       'quadriceps',  ARRAY['glutes', 'hamstrings', 'lower_back'],   'barbell',    'intermediate'),
    ('Front Squat',                    'weight_reps',       'quadriceps',  ARRAY['glutes', 'abs'],                        'barbell',    'advanced'),
    ('Leg Press',                      'weight_reps',       'quadriceps',  ARRAY['glutes', 'hamstrings'],                 'machine',    'beginner'),
    ('Bulgarian Split Squat',          'weight_reps',       'quadriceps',  ARRAY['glutes', 'hamstrings'],                 'dumbbell',   'intermediate'),
    ('Leg Extension',                  'weight_reps',       'quadriceps',  ARRAY[]::TEXT[],                               'machine',    'beginner'),
    ('Walking Lunge',                  'weight_reps',       'quadriceps',  ARRAY['glutes', 'hamstrings'],                 'dumbbell',   'beginner'),
    ('Conventional Deadlift',          'weight_reps',       'lower_back',  ARRAY['glutes', 'hamstrings', 'traps', 'forearms'], 'barbell', 'intermediate'),
    ('Romanian Deadlift',              'weight_reps',       'hamstrings',  ARRAY['glutes', 'lower_back'],                 'barbell',    'intermediate'),
    ('Lying Leg Curl',                 'weight_reps',       'hamstrings',  ARRAY[]::TEXT[],                               'machine',    'beginner'),
    ('Hip Thrust',                     'weight_reps',       'glutes',      ARRAY['hamstrings'],                           'barbell',    'intermediate'),
    ('Kettlebell Swing',               'weight_reps',       'glutes',      ARRAY['hamstrings', 'lower_back', 'shoulders'], 'kettlebell', 'intermediate'),
    ('Standing Calf Raise',            'weight_reps',       'calves',      ARRAY[]::TEXT[],                               'machine',    'beginner'),
    ('Pull-Up',                        'reps',              'lats',        ARRAY['biceps', 'upper_back'],                 'none',       'intermediate'),
    ('Chin-Up',                        'reps',              'lats',        ARRAY['biceps'],                               'none',       'intermediate'),
    ('Lat Pulldown',                   'weight_reps',       'lats',        ARRAY['biceps', 'upper_back'],                 'cable',      'beginner'),
    ('One-Arm Dumbbell Row',           'weight_reps',       'lats',        ARRAY['upper_back', 'biceps'],                 'dumbbell',   'beginner'),
    ('Barbell Row',                    'weight_reps',       'upper_back',  ARRAY['lats', 'biceps', 'lower_back'],         'barbell',    'intermediate'),
    ('Seated Cable Row',               'weight_reps',       'upper_back',  ARRAY['lats', 'biceps'],                       'cable',      'beginner'),
    ('Barbell Shrug',                  'weight_reps',       'traps',       ARRAY['forearms'],                             'barbell',    'beginner'),
    ('Overhead Press',                 'weight_reps',       'shoulders',   ARRAY['triceps'],                              'barbell',    'intermediate'),
    ('Seated Dumbbell Shoulder Press', 'weight_reps',       'shoulders',   ARRAY['triceps'],                              'dumbbell',   'beginner'),
    ('Lateral Raise',                  'weight_reps',       'shoulders',   ARRAY[]::TEXT[],                               'dumbbell',   'beginner'),
    ('Rear Delt Fly',                  'weight_reps',       'shoulders',   ARRAY['upper_back'],                           'dumbbell',   'beginner'),
    ('Face Pull',                      'weight_reps',       'shoulders',   ARRAY['upper_back', 'traps'],                  'cable',      'beginner'),
    ('Barbell Curl',                   'weight_reps',       'biceps',      ARRAY['forearms'],                             'barbell',    'beginner'),
    ('Hammer Curl',                    'weight_reps',       'biceps',      ARRAY['forearms'],                             'dumbbell',   'beginner'),
    ('Incline Dumbbell Curl',          'weight_reps',       'biceps',      ARRAY[]::TEXT[],                               'dumbbell',   'beginner'),
    ('Triceps Pushdown',               'weight_reps',       'triceps',     ARRAY[]::TEXT[],                               'cable',      'beginner'),
    ('Skull Crusher',                  'weight_reps',       'triceps',     ARRAY[]::TEXT[],                               'barbell',    'intermediate'),
    ('Overhead Triceps Extension',     'weight_reps',       'triceps',     ARRAY[]::TEXT[],                               'dumbbell',   'beginner'),
    ('Close-Grip Bench Press',         'weight_reps',       'triceps',     ARRAY['chest', 'shoulders'],                   'barbell',    'intermediate'),
    ('Wrist Curl',                     'weight_reps',       'forearms',    ARRAY[]::TEXT[],                               'dumbbell',   'beginner'),
    ('Plank',                          'duration',          'abs',         ARRAY['shoulders'],                            'none',       'beginner'),
    ('Hanging Leg Raise',              'reps',              'abs',         ARRAY['forearms'],                             'none',       'intermediate'),
    ('Cable Crunch',                   'weight_reps',       'abs',         ARRAY[]::TEXT[],                               'cable',      'beginner'),
    ('Ab Wheel Rollout',               'reps',              'abs',         ARRAY['lats', 'shoulders'],                    'other',      'intermediate'),
    ('Burpee',                         'reps',              'full_body',   ARRAY['chest', 'quadriceps'],                  'none',       'beginner'),
    ('Treadmill Run',                  'distance_duration', 'cardio',      ARRAY['quadriceps', 'calves'],                 'machine',    'beginner'),
    ('Rowing Machine',                 'distance_duration', 'cardio',      ARRAY['upper_back', 'quadriceps'],             'machine',    'beginner'),
    ('Stationary Bike',                'distance_duration', 'cardio',      ARRAY['quadriceps'],                           'machine',    'beginner'),
    ('Jump Rope',                      'duration',          'cardio',      ARRAY['calves'],                               'other',      'beginner')
) AS catalog (name, tracking, primary_muscle, secondary_muscles, equipment, difficulty);
